version: '3.9'

services:

  db:
    image: postgres
    # IRL, these would not be hardcoded. They would be injected as environment variables.
    environment:
      POSTGRES_DB: chore_tracker
      POSTGRES_PASSWORD: choretrackerservicepassword
      POSTGRES_USER: chore-tracker-service
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U chore-tracker-service -d chore_tracker" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    ports:
      - 5432:5432
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 1gb
