BEGIN;

CREATE TABLE IF NOT EXISTS child (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    age SMALLINT  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE IF NOT EXISTS chore (
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    price DECIMAL(5, 2) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC')
);

CREATE TABLE IF NOT EXISTS chore_completion (
    id SERIAL PRIMARY KEY,
    child_id INTEGER NOT NULL,
    chore_id INTEGER NOT NULL,
    completed_timestamp BIGINT NOT NULL,
    paid BOOLEAN NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT fk_chore_completion_child_id FOREIGN KEY(child_id) REFERENCES child(id),
    CONSTRAINT fk_chore_completion_chore_id FOREIGN KEY(chore_id) REFERENCES chore(id)
);

COMMIT;